/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.UIManager;

/**
 *
 * @author SoftEngineer jay
 */
public class Mainframe extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    public Mainframe() {
        initComponents();
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelbody = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BTN1 = new javax.swing.JPanel();
        PN1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        BTN2 = new javax.swing.JPanel();
        PN2 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        BTN3 = new javax.swing.JPanel();
        PN3 = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        BTN4 = new javax.swing.JPanel();
        PN4 = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        BTN5 = new javax.swing.JPanel();
        PN5 = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        BTN6 = new javax.swing.JPanel();
        PN6 = new javax.swing.JPanel();
        label6 = new javax.swing.JLabel();
        BTN7 = new javax.swing.JPanel();
        PN7 = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        BTN8 = new javax.swing.JPanel();
        PN8 = new javax.swing.JPanel();
        label8 = new javax.swing.JLabel();
        BTN9 = new javax.swing.JPanel();
        PN9 = new javax.swing.JPanel();
        label9 = new javax.swing.JLabel();
        paneltop = new javax.swing.JPanel();
        label_user = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cardpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        count5 = new javax.swing.JLabel();
        count1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        count6 = new javax.swing.JLabel();
        count2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        count7 = new javax.swing.JLabel();
        count3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        count8 = new javax.swing.JLabel();
        count4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 650));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        panelbody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(36, 37, 42));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_manager_127px_1.png"))); // NOI18N
        sidebar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, 240, 130));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("administrator");
        sidebar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 250, 24));

        BTN1.setBackground(new java.awt.Color(30, 139, 195));
        BTN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN1MouseClicked(evt);
            }
        });

        PN1.setBackground(new java.awt.Color(30, 139, 195));

        javax.swing.GroupLayout PN1Layout = new javax.swing.GroupLayout(PN1);
        PN1.setLayout(PN1Layout);
        PN1Layout.setHorizontalGroup(
            PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        PN1Layout.setVerticalGroup(
            PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Dashboard");
        label1.setIconTextGap(10);

        javax.swing.GroupLayout BTN1Layout = new javax.swing.GroupLayout(BTN1);
        BTN1.setLayout(BTN1Layout);
        BTN1Layout.setHorizontalGroup(
            BTN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN1Layout.createSequentialGroup()
                .addComponent(PN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        BTN1Layout.setVerticalGroup(
            BTN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(BTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 270, 50));

        BTN2.setBackground(new java.awt.Color(36, 37, 42));
        BTN2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN2MouseClicked(evt);
            }
        });

        PN2.setBackground(new java.awt.Color(30, 139, 195));
        PN2.setOpaque(false);

        javax.swing.GroupLayout PN2Layout = new javax.swing.GroupLayout(PN2);
        PN2.setLayout(PN2Layout);
        PN2Layout.setHorizontalGroup(
            PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        PN2Layout.setVerticalGroup(
            PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Title");
        label2.setIconTextGap(10);

        javax.swing.GroupLayout BTN2Layout = new javax.swing.GroupLayout(BTN2);
        BTN2.setLayout(BTN2Layout);
        BTN2Layout.setHorizontalGroup(
            BTN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN2Layout.createSequentialGroup()
                .addComponent(PN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        BTN2Layout.setVerticalGroup(
            BTN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(BTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 270, 50));

        BTN3.setBackground(new java.awt.Color(36, 37, 42));
        BTN3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PN3.setBackground(new java.awt.Color(30, 139, 195));
        PN3.setOpaque(false);

        javax.swing.GroupLayout PN3Layout = new javax.swing.GroupLayout(PN3);
        PN3.setLayout(PN3Layout);
        PN3Layout.setHorizontalGroup(
            PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        PN3Layout.setVerticalGroup(
            PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Title");
        label3.setIconTextGap(10);

        javax.swing.GroupLayout BTN3Layout = new javax.swing.GroupLayout(BTN3);
        BTN3.setLayout(BTN3Layout);
        BTN3Layout.setHorizontalGroup(
            BTN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN3Layout.createSequentialGroup()
                .addComponent(PN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        BTN3Layout.setVerticalGroup(
            BTN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(BTN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 270, 50));

        BTN4.setBackground(new java.awt.Color(36, 37, 42));
        BTN4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PN4.setBackground(new java.awt.Color(30, 139, 195));
        PN4.setOpaque(false);

        javax.swing.GroupLayout PN4Layout = new javax.swing.GroupLayout(PN4);
        PN4.setLayout(PN4Layout);
        PN4Layout.setHorizontalGroup(
            PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        PN4Layout.setVerticalGroup(
            PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Title");
        label4.setIconTextGap(10);

        javax.swing.GroupLayout BTN4Layout = new javax.swing.GroupLayout(BTN4);
        BTN4.setLayout(BTN4Layout);
        BTN4Layout.setHorizontalGroup(
            BTN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN4Layout.createSequentialGroup()
                .addComponent(PN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        BTN4Layout.setVerticalGroup(
            BTN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(BTN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 270, 50));

        BTN5.setBackground(new java.awt.Color(36, 37, 42));
        BTN5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PN5.setBackground(new java.awt.Color(30, 139, 195));
        PN5.setOpaque(false);

        javax.swing.GroupLayout PN5Layout = new javax.swing.GroupLayout(PN5);
        PN5.setLayout(PN5Layout);
        PN5Layout.setHorizontalGroup(
            PN5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        PN5Layout.setVerticalGroup(
            PN5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Title");
        label5.setIconTextGap(10);

        javax.swing.GroupLayout BTN5Layout = new javax.swing.GroupLayout(BTN5);
        BTN5.setLayout(BTN5Layout);
        BTN5Layout.setHorizontalGroup(
            BTN5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN5Layout.createSequentialGroup()
                .addComponent(PN5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        BTN5Layout.setVerticalGroup(
            BTN5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(BTN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 270, 50));

        BTN6.setBackground(new java.awt.Color(36, 37, 42));
        BTN6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PN6.setBackground(new java.awt.Color(30, 139, 195));
        PN6.setOpaque(false);

        javax.swing.GroupLayout PN6Layout = new javax.swing.GroupLayout(PN6);
        PN6.setLayout(PN6Layout);
        PN6Layout.setHorizontalGroup(
            PN6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        PN6Layout.setVerticalGroup(
            PN6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("Title");
        label6.setIconTextGap(10);

        javax.swing.GroupLayout BTN6Layout = new javax.swing.GroupLayout(BTN6);
        BTN6.setLayout(BTN6Layout);
        BTN6Layout.setHorizontalGroup(
            BTN6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN6Layout.createSequentialGroup()
                .addComponent(PN6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        BTN6Layout.setVerticalGroup(
            BTN6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(BTN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, 50));

        BTN7.setBackground(new java.awt.Color(36, 37, 42));
        BTN7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PN7.setBackground(new java.awt.Color(30, 139, 195));
        PN7.setOpaque(false);

        javax.swing.GroupLayout PN7Layout = new javax.swing.GroupLayout(PN7);
        PN7.setLayout(PN7Layout);
        PN7Layout.setHorizontalGroup(
            PN7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        PN7Layout.setVerticalGroup(
            PN7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("Chart");
        label7.setIconTextGap(10);

        javax.swing.GroupLayout BTN7Layout = new javax.swing.GroupLayout(BTN7);
        BTN7.setLayout(BTN7Layout);
        BTN7Layout.setHorizontalGroup(
            BTN7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN7Layout.createSequentialGroup()
                .addComponent(PN7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        BTN7Layout.setVerticalGroup(
            BTN7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(BTN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 270, 50));

        BTN8.setBackground(new java.awt.Color(36, 37, 42));
        BTN8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PN8.setBackground(new java.awt.Color(30, 139, 195));
        PN8.setOpaque(false);

        javax.swing.GroupLayout PN8Layout = new javax.swing.GroupLayout(PN8);
        PN8.setLayout(PN8Layout);
        PN8Layout.setHorizontalGroup(
            PN8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        PN8Layout.setVerticalGroup(
            PN8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setText("Setting");
        label8.setIconTextGap(10);

        javax.swing.GroupLayout BTN8Layout = new javax.swing.GroupLayout(BTN8);
        BTN8.setLayout(BTN8Layout);
        BTN8Layout.setHorizontalGroup(
            BTN8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN8Layout.createSequentialGroup()
                .addComponent(PN8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        BTN8Layout.setVerticalGroup(
            BTN8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(BTN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, 50));

        BTN9.setBackground(new java.awt.Color(36, 37, 42));
        BTN9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PN9.setBackground(new java.awt.Color(30, 139, 195));
        PN9.setOpaque(false);

        javax.swing.GroupLayout PN9Layout = new javax.swing.GroupLayout(PN9);
        PN9.setLayout(PN9Layout);
        PN9Layout.setHorizontalGroup(
            PN9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        PN9Layout.setVerticalGroup(
            PN9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setText("Log-Out");
        label9.setIconTextGap(10);

        javax.swing.GroupLayout BTN9Layout = new javax.swing.GroupLayout(BTN9);
        BTN9.setLayout(BTN9Layout);
        BTN9Layout.setHorizontalGroup(
            BTN9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN9Layout.createSequentialGroup()
                .addComponent(PN9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        BTN9Layout.setVerticalGroup(
            BTN9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(BTN9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 270, 50));

        panelbody.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 650));

        paneltop.setBackground(new java.awt.Color(37, 116, 169));
        paneltop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_user.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_user.setForeground(new java.awt.Color(255, 255, 255));
        label_user.setText("USER");
        paneltop.add(label_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 18, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Title System");
        paneltop.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 11, 390, 38));

        Date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Date.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_today_35px_2.png"))); // NOI18N
        Date.setText("Date");
        paneltop.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 11, 210, 38));

        Time.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_clock_35px_3.png"))); // NOI18N
        Time.setText("Time");
        paneltop.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 11, 170, 38));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_user_male_circle_35px.png"))); // NOI18N
        paneltop.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 48, 36));

        panelbody.add(paneltop, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1030, 60));

        cardpanel.setLayout(new java.awt.CardLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dashboard", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(30, 139, 195));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(51, 153, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("User");
        jLabel9.setOpaque(true);
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        count5.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        count5.setForeground(new java.awt.Color(255, 255, 255));
        count5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_groups_60px_1.png"))); // NOI18N
        count5.setIconTextGap(10);
        jPanel11.add(count5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 85, 70));

        count1.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        count1.setForeground(new java.awt.Color(255, 255, 255));
        count1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count1.setText("0");
        count1.setIconTextGap(10);
        jPanel11.add(count1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 59, 110, 70));
        jPanel11.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Updated every 30 min");
        jPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, -1));

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, 170));

        jPanel12.setBackground(new java.awt.Color(30, 130, 76));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 177, 106));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Title");
        jLabel11.setOpaque(true);
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        count6.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        count6.setForeground(new java.awt.Color(255, 255, 255));
        count6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_groups_60px_1.png"))); // NOI18N
        count6.setIconTextGap(10);
        jPanel12.add(count6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 85, 70));

        count2.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        count2.setForeground(new java.awt.Color(255, 255, 255));
        count2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count2.setText("0");
        count2.setIconTextGap(10);
        jPanel12.add(count2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 59, 110, 70));
        jPanel12.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Updated every 30 min");
        jPanel12.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, -1));

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 230, 170));

        jPanel13.setBackground(new java.awt.Color(150, 40, 27));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(207, 0, 15));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Title");
        jLabel12.setOpaque(true);
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        count7.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        count7.setForeground(new java.awt.Color(255, 255, 255));
        count7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_groups_60px_1.png"))); // NOI18N
        count7.setIconTextGap(10);
        jPanel13.add(count7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 85, 70));

        count3.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        count3.setForeground(new java.awt.Color(255, 255, 255));
        count3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count3.setText("0");
        count3.setIconTextGap(10);
        jPanel13.add(count3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 59, 110, 70));
        jPanel13.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Updated every 30 min");
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, -1));

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 230, 170));

        jPanel14.setBackground(new java.awt.Color(0, 51, 102));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(0, 102, 153));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Title");
        jLabel13.setOpaque(true);
        jPanel14.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        count8.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        count8.setForeground(new java.awt.Color(255, 255, 255));
        count8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_groups_60px_1.png"))); // NOI18N
        count8.setIconTextGap(10);
        jPanel14.add(count8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 85, 70));

        count4.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        count4.setForeground(new java.awt.Color(255, 255, 255));
        count4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count4.setText("0");
        count4.setIconTextGap(10);
        jPanel14.add(count4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 59, 110, 70));
        jPanel14.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Updated every 30 min");
        jPanel14.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, -1));

        jPanel6.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 230, 170));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        cardpanel.add(jPanel1, "card2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        cardpanel.add(jPanel2, "card3");

        panelbody.add(cardpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 1030, 590));

        getContentPane().add(panelbody);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN1MouseClicked
        cardpanel.removeAll();
        cardpanel.repaint();
        cardpanel.revalidate();
        cardpanel.add(jPanel1);
        cardpanel.repaint();
        cardpanel.revalidate();

    }//GEN-LAST:event_BTN1MouseClicked

    private void BTN2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN2MouseClicked
        cardpanel.removeAll();
        cardpanel.repaint();
        cardpanel.revalidate();
        cardpanel.add(jPanel2);
        cardpanel.repaint();
        cardpanel.revalidate();
    }//GEN-LAST:event_BTN2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BTN1;
    private javax.swing.JPanel BTN2;
    private javax.swing.JPanel BTN3;
    private javax.swing.JPanel BTN4;
    private javax.swing.JPanel BTN5;
    private javax.swing.JPanel BTN6;
    private javax.swing.JPanel BTN7;
    private javax.swing.JPanel BTN8;
    private javax.swing.JPanel BTN9;
    private javax.swing.JLabel Date;
    private javax.swing.JPanel PN1;
    private javax.swing.JPanel PN2;
    private javax.swing.JPanel PN3;
    private javax.swing.JPanel PN4;
    private javax.swing.JPanel PN5;
    private javax.swing.JPanel PN6;
    private javax.swing.JPanel PN7;
    private javax.swing.JPanel PN8;
    private javax.swing.JPanel PN9;
    private javax.swing.JLabel Time;
    private javax.swing.JPanel cardpanel;
    private javax.swing.JLabel count1;
    private javax.swing.JLabel count2;
    private javax.swing.JLabel count3;
    private javax.swing.JLabel count4;
    private javax.swing.JLabel count5;
    private javax.swing.JLabel count6;
    private javax.swing.JLabel count7;
    private javax.swing.JLabel count8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    public static javax.swing.JLabel label_user;
    private javax.swing.JPanel panelbody;
    private javax.swing.JPanel paneltop;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
